FROM ubuntu:noble

RUN  apt update && apt install -y gpg wget lsb-release software-properties-common

RUN wget -O- https://apt.releases.hashicorp.com/gpg |  gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

RUN gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |  tee /etc/apt/sources.list.d/hashicorp.list

RUN add-apt-repository ppa:deadsnakes/ppa

RUN  apt update && apt -y install vault python3.11 python3.11-venv

RUN mkdir /app

WORKDIR /app

COPY ./app/* ./

RUN apt install -y python3-flask python3-psycopg2 vim netcat-traditional

RUN chmod +x start.sh

ENTRYPOINT  [  "/app/start.sh" ] 